#!/usr/bin/env bash

session=$(find . -mindepth 1 -maxdepth 1 -type d | fzf)

session_name=$(basename "$session" | tr . _ | cut -c 1-6)

if ! tmux has-session -t  "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d 
fi

tmux switch-client -t "$session_name"

#tmux list-sessions | cut -d: -f1 | grep -v "^$session_name$" | xargs -I{} tmux kill-session -t {}
